### Index method
GET http://localhost:3000/api/watchlists

### Successfully create watchlist
POST http://localhost:3000/api/watchlists
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3MTA2MjMsInN1YiI6MX0.VgUOMdCJ-wvpJg8ACaByKSfsNY3hXnbO9T9LR16z-Jc

{
  "movie_id": 23,
  "title": "Totoro"
}

### Unsuccessfully create watchlist
POST http://localhost:3000/api/watchlists
Content-Type: application/json

{
}

### Successfully show watchlist id: 1
GET http://localhost:3000/api/watchlists/1

### Unsuccessfuly show watchlist id: 1000
GET http://localhost:3000/api/watchlists/1000

### Successfully delete watchlist id: 1
DELETE http://localhost:3000/api/watchlists/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3ODgwMjksInN1YiI6MX0.3x2ZDVDtTsNA1zuQxcrw7wKraBxT_ab8_3dhOVpX-oE

### Unsuccessfully delete watchlist id: 2. Not creator of watchlist.
DELETE http://localhost:3000/api/watchlists/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3ODgwMjksInN1YiI6MX0.3x2ZDVDtTsNA1zuQxcrw7wKraBxT_ab8_3dhOVpX-oE


### Unsuccessfully delete watchlist id: 1000. No existing watchlist.
DELETE http://localhost:3000/api/watchlists/1000
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3ODgwMjksInN1YiI6MX0.3x2ZDVDtTsNA1zuQxcrw7wKraBxT_ab8_3dhOVpX-oE

### Successfully create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "username": "Sally", 
  "email": "sally@test.com",
  "password": "password6",
  "password_confirmation": "password6"
}

### Successfully sign_in˛
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "sally@test.com",
  "password": "password6"
}

### Unsuccessful sign_in
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "barry@test.com",
  "password": "password"
}

### Successfully update username
PUT http://localhost:3000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3OTQ4NjYsInN1YiI6NH0.oJgK57MlBfW56BbTyIkU4QRibXnOOplbkOGnIbjskdQ

{
  "username": "Fally" 
}

### Successfully update email
PUT http://localhost:3000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3OTQ4NjYsInN1YiI6NH0.oJgK57MlBfW56BbTyIkU4QRibXnOOplbkOGnIbjskdQ

{
  "email": "Fally@test.com" 
}

### Successfully sign_in˛with updated email
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "Fally@test.com",
  "password": "password6"
}

### Successfully update password
PUT http://localhost:3000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3OTQ4NjYsInN1YiI6NH0.oJgK57MlBfW56BbTyIkU4QRibXnOOplbkOGnIbjskdQ

{
  "password": "password456"
}

### Successfully sign_in˛with updated password
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "Fally@test.com",
  "password": "password456"
}

### Successfully delete current_user id: 1
DELETE http://localhost:3000/api/auth/delete
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3OTgyMTAsInN1YiI6MX0.vg3qhbKgbcBmXbAf3s6rnleqsClIzE612p12y6wt30M
